image: openjdk:11-stretch

stages:
  - build
  - test

before_script:
  - echo "Start CI/CD"

build:
  stage: build
  script:
    - ./gradlew assemble
  artifacts:
    paths:
      - build/libs/*.jar
    expire_in: 1 week
  only:
    - master
    - develop
    - release

test:
  stage: test
  script:
    - ./gradlew check
  only:
    - master
    - develop
    - release

after_script:
  - echo "End CI/CD"